# Goal: To deploy the built images from CI Steps once the CI Worklow is Succeeded
# Goal: To deploy the built images from CI Steps once the CI Worklow is Succeeded
name: CD

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      # This action securely logs into your EC2 server and triggers the deployment there
      - name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/devboard/
            docker compose pull
            docker compose up -d --force-recreate

