# Goal: To deploy the built images from CI Steps once the CI Worklow is Succeeded

name: CD

on: 
    workflow_call:

jobs:
    deploy:
        
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v7

            - name: Copy Example Env to main env
              run: cp .env.example .env

            - name: Docker Setup [Login]
              uses: docker/login-action@v4
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Deploy the containers with Docker Compose
              run: |
                docker compose pull
                docker compose up -d
