# Goal Push the images to DockerHub# Goal Push the images to DockerHub
name: Docker Push

on:
  workflow_call:

jobs:
  frontend:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        folders: ['backend','frontend']
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Setup [Login]
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build and Push
        uses: docker/build-push-action@v7
        with:
          # Restore the original folder context so files like go.sum are found cleanly
          context: ./${{ matrix.folders }}
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/devboard-${{ matrix.folders }}:latest
          # Keeps the cache disabled so your new text updates are compiled fresh
          no-cache: true 
          
 
#
